
include: package:mews_pedantic/analysis_options.yaml

linter:

  rules:
    avoid_print: false 
    prefer_single_quotes: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore